# Generated by Django 5.2.6 on 2025-09-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('installed', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('schema', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
