# Generated by Django 5.2.6 on 2025-09-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modengine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='version',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
    ]
